### ISSUE TITLE
Создание интерактивной странички к Новому году, на которой пользователь сможет упаковать подарок, сделав пожертвование.  - задача дададзена [11/20/2017 12:53:54]

### ISSUE THREAD

**Issue by falanster** [diglabby/tasks#27]
Коратка пра ініцыятыву: SOS-Детские деревни Беларусь уже 25 лет является единственной негосударственной организацией, которая полностью взяла на себя всю ответственность, заботы и хлопоты по воспитанию детей-сирот. Каждому из наших воспитанников мы стараемся подарить счастливое детство и дать достойный старт во взрослую жизнь.
На сегодняшний день в трех SOS-Детских деревнях и двух SOS-Молодежных домах Беларуси (в Боровлянах, Марьиной Горке и Могилёве) проживает 287 детей–сирот. Помимо этого, мы работаем в сфере предотвращения социального сиротства, поддерживаем детей в их праве на достойное и качественное образование, помогаем детям с онко-гематологическими заболеваниями, женщинам и детям, пострадавшим от домашнего насилия, молодым матерям с маленькими детьми.
Патрэба ініцыятывы: Создание страницы, на которой будет размещена виртуальная коробочка с подарком, где можно будет выбрать цвет упаковки и завязать бантик, написать пожелание, например. И положить подарок из выбранного списка (будет осуществляться переход на страницу с интернет-оплатой, такая страница уже есть, нужно привязать). 
Похожий по логике проект был реализован российской благотворительной организацией (там было украшение елки). https://downsideup.org/4emdalshevles/#/group/0/tree/1

**Comment by koverchik** [comment]
Отличная инициатива. Я всеми руками за и готова отверстать страницу. Судя по всему нужно сделать это в короткие сроки. Нужен дизайнер и побольше информации.

**Comment by daryasolomina** [comment]
Могу предложить такой вариант (по-быстрому накидала)
https://cloud.mail.ru/public/A8PC/MBVPK4YZu
Если такого плана подходит - доделаем.

**Comment by falanster** [comment]
@koverchik @daryasolomina 

што вам яшчэ неабходня для старта? як ацэнваеце час на рэалізацыю?

**Comment by daryasolomina** [comment]
Такой вариант макета подошел? Дополнения от заказчика нужны: какая точно информация должна быть на странице, какой список подарков. Сколько вариантов коробок сделать.

**Comment by katebel** [comment]
@koverchik @daryasolomina 
Привет, спасибо, что откликнулись) @daryasolomina , спасибо за макет, очень неплохо, поработаем с ним) времени действительно немного, но думаю, нам вместе удастся справиться с поставленной задачей) я координирую данную акцию от SOS-Детских деревень. предлагаю создать диалог в каком-либо мессенджере (вайбер, телеграмм или вк?). Скиньте на мою почту katsiaryna.bialevich@sos-by.org свои контактные данные, я создам совместный диалог, где уже подробно все с вами обсудим)
